### ISSUE TITLE
How can i append the data to an existing JSON file?

### ISSUE THREAD

**Issue by talvasconcelos** [jon49/gulp-pluck#1]
Hi, how can i append the data i get from front-matter to an existing json file? Here's what i have:

`gulp.task('meta', function(){
  return gulp.src(path.posts)
    .pipe(plumber({
      handleError: onError
    }))
    .pipe(frontMatter({ property: 'meta'}))
    //.pipe(data(function(file){
    //        file.meta.path = file.path
    //    }))
    .pipe(pluck('meta', 'meta.json'))
    .pipe(data(function(file){
        file.contents = new Buffer(JSON.stringify({'articles': file.meta}, null, '  '));
        //var obj = JSON.parse(require './config.json');
        //obj.articles = file.contents;

```
}))
.pipe(gulp.dest('dev/articles/'))
```

});`

At the moment it outputs to a meta.json file, i'd like for it to append the data to an existing config.json under an "artilcles" key.

Thanks,
Tiago

**Comment by jon49** [comment]
Not sure how you would do that. You could ask on stackoverflow.
I don't use `gulp` right now. There is probably a plugin for that.
