### ISSUE TITLE
Adds support to yarn

### ISSUE THREAD

**Issue by pragmaticivan** [jon49/gulp-pluck#2]
The node version on this package.json causes an error:

```
error gulp-pluck@0.0.2: The engine "node" is incompatible with this module. Expected version ">= ?".
error Found incompatible module
```

definition:
```
"engines": {
    "node": ">= ?"
  },
```

**Comment by jon49** [comment]
Please put in a pull request and I'll accept it. I don't really program with node on the back end anymore. So, I'm not familiar with all the issues involved.

**Comment by zenorocha** [comment]
Just sent a PR :)

**Comment by zenorocha** [comment]
Thanks @jon49!

**Comment by jon49** [comment]
NP, thanks for putting in the pull request!
